name: Cloud functional tests
on:
  schedule:
    - cron:  '0 3 * * 1,3,5' # runs at 3am monday wednesday and friday
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  rest:
    name: Test against remote AWS account
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-linux-release'
      GEN: ninja
      VCPKG_FEATURE_FLAGS: "-binarycaching"
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - name: Install required ubuntu packages
        run: |
          sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ce613c41372b23b1f51333815feb3edd87ef8a8b

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        continue-on-error: true

      - name: Build extension
        env:
          GEN: ninja
          STATIC_LIBCPP: 1
        run: |
          make release

      - name: install python packages
        run: |
          python3 -m pip install scripts/requirements.txt

      - name: Set up cloud testing
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.S3_ICEBERG_TEST_USER_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.S3_ICEBERG_TEST_USER_SECRET}}
          AWS_DEFAULT_REGION: ${{secrets.S3_ICEBERG_TEST_USER_REGION}}
          r2_token: ${{secrets.r2_token}}
        run: | 
          python3 scripts/create_insert_table.py --action=delete-and-create --catalogs=s3tables,r2,glue

      - name: Test with rest catalog
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.S3_ICEBERG_TEST_USER_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.S3_ICEBERG_TEST_USER_SECRET}}
          AWS_DEFAULT_REGION: ${{secrets.S3_ICEBERG_TEST_USER_REGION}}
          ICEBERG_REMOTE_INSERT_READY: 1
          ICEBERG_AWS_REMOTE_AVAILABLE: 1
        run: |
          make test_release

      - name: File issue if error
        if: failure()
        run: |
          echo "Cloud tests failed. see [Run Link](https://github.com/duckdblabs/duckdb-internal/actions/runs/${{ github.run_id }})" > report.txt
          gh issue create --repo duckdb/duckdb-iceberg --title "Cloud Test Failures" --body-file report.txt