name: Local functional tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

env:
  BASE_BRANCH: ${{ github.base_ref || (endsWith(github.ref, '_feature') && 'feature' || 'main') }}
  CMAKE_POLICY_VERSION_MINIMUM: 3.5

jobs:
  rest:
    name: Test against local Rest Catalog
    runs-on: ubuntu-latest
    env:
      VCPKG_TARGET_TRIPLET: 'x64-linux'
      GEN: ninja
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - name: Install required ubuntu packages
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq \
            ninja-build \
            make gcc-multilib \
            g++-multilib \
            libssl-dev \
            wget \
            openjdk-8-jdk \
            zip \
            maven \
            unixodbc-dev \
            libc6-dev-i386 \
            lib32readline6-dev \
            libssl-dev \
            libcurl4-gnutls-dev \
            libexpat1-dev \
            gettext \
            unzip \
            build-essential \
            checkinstall \
            libffi-dev \
            curl \
            libz-dev \
            openssh-client
          sudo apt-get install -y -qq tar pkg-config
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install CMake 3.x
        run: |
          sudo apt-get remove -y cmake cmake-data
          sudo apt-get install --allow-downgrades -y -qq 'cmake=3.*' 'cmake-data=3.*'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Check installed versions
        run: |
          ninja --version
          cmake --version

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: 5e5d0e1cd7785623065e77eff011afdeec1a3574

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        continue-on-error: true

      - name: Build extension
        env:
          GEN: ninja
          STATIC_LIBCPP: 1
        run: |
          make release

      - name: Generate data
        run: |
          make data

      - name: Test with rest catalog
        env:
          ICEBERG_SERVER_AVAILABLE: 1
          DUCKDB_ICEBERG_HAVE_GENERATED_DATA: 1
        run: |
          make test_release

      - name: Set up for Polaris
        run: |
          # install java
          sudo apt install -y -qq openjdk-21-jre-headless
          sudo apt install -y -qq openjdk-21-jdk-headless
          # install python virtual environment (is this needed?)
          sudo apt-get install -y -qq python3-venv
          
      - name: Setup Jenv
        run: |
          git clone https://github.com/jenv/jenv.git ~/.jenv
          echo 'export PATH="$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile
          eval "$(jenv init -)"
          jenv enable-plugin export
          exec $SHELL -l
          jenv add /usr/lib/jvm/java-21-openjdk-amd64

      - name: Setup Polaris
        run: |
          make setup_polaris
          # let polaris initialize 
          sleep 30
          python3 -m venv .
          source ./bin/activate
          python3 -m pip install poetry
          python3 -m pip install pyspark==3.5.0
          python3 scripts/polaris/get_polaris_root_creds.py
          # needed for setup_polaris_catalog.sh
          export POLARIS_ROOT_ID=$(cat polaris_root_id.txt)
          export POLARIS_ROOT_SECRET=$(cat polaris_root_password.txt)
          cd polaris_catalog && ../scripts/polaris/setup_polaris_catalog.sh > user_credentials.json
          cd ..
          python3 scripts/polaris/get_polaris_client_creds.py
          export POLARIS_CLIENT_ID=$(cat polaris_client_id.txt)
          export POLARIS_CLIENT_SECRET=$(cat polaris_client_secret.txt)
          python3 scripts/polaris/create_data.py

      - name: Test with rest catalog
        env:
          POLARIS_SERVER_AVAILABLE: 1
        run: |
          export POLARIS_CLIENT_ID=$(cat polaris_client_id.txt)
          export POLARIS_CLIENT_SECRET=$(cat polaris_client_secret.txt)
          make test_release