#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.3.2
    with:
      extension_name: iceberg
      duckdb_version: v1.3.2
      ci_tools_version: main
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw;linux_amd64_gcc4'
      extra_toolchains: 'python3'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.3.2
    secrets: inherit
    with:
      extension_name: iceberg
      duckdb_version: v1.3.2
      ci_tools_version: main
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools;windows_amd64_mingw;linux_amd64_gcc4'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}

  duckdb-wasm-build:
    if: ${{ github.ref == 'refs/heads/wasm' }}
    name: Build extension binaries for duckdb-wasm (experimental)
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      extension_name: iceberg
      duckdb_version: v1.3.2
      ci_tools_version: main
      exclude_archs: 'windows_amd64_rtools;windows_amd64_mingw;linux_amd64_gcc4;linux_amd64;linux_arm64;osx_arm64;osx_amd64;windows_amd64'
      extra_toolchains: 'python3'

  duckdb-wasm-deploy:
    name: Deploy extension binaries for duckdb-wasm (experimental)
    needs: duckdb-wasm-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      extension_name: iceberg
      duckdb_version: v1.3.2
      ci_tools_version: main
      exclude_archs: 'windows_amd64_rtools;windows_amd64_mingw;linux_amd64_gcc4;linux_amd64;linux_arm64;osx_arm64;osx_amd64;windows_amd64'
      deploy_latest: ${{ github.ref == 'refs/heads/wasm' }}
      deploy_versioned: ${{ github.ref == 'refs/heads/wasm' }}
